sudo: false
language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"

branches:
  only:
    - master
    - /^\d+\.\d+$/
    - php7

before_script:
  - composer install --dev
  - php -i | grep -A 2 "fileinfo support"

script: ./phpunit
