sudo: false
language: php

php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

branches:
  only:
    - master
    - /^\d+\.\d+$/
    - magic-experiments

before_script:
  - composer install --dev
  - php -i | grep -A 2 "fileinfo support"

script: ./phpunit
